#!/usr/bin/env python3
"""Auto-generate the 17 "Browse by topic" sphinx pages from help.json.

Output:
    docs/by_topic_index.rst      -- index page with a toctree of 17 topics
    docs/by_topic/<topic>.rst    -- one page per topic listing its members

Run after every help.json update:
    poetry run python devtools/build_topic_pages.py

The output files are committed to the repo so GitHub renders them too.
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
HELP_JSON = ROOT / "screamer" / "data" / "help.json"
OUT_DIR = ROOT / "docs" / "by_topic"
INDEX_FILE = ROOT / "docs" / "by_topic_index.rst"

# Topic display titles + 1-line descriptions. Order is alphabetical by
# topic key (= filename); the title in the page header drives the
# sidebar label sphinx renders.
TOPICS: dict[str, tuple[str, str]] = {
    "activation":         ("Activation",
                           "Neural-network-style nonlinearities. Useful as composition primitives for feature engineering."),
    "channels":           ("Channels",
                           "Bands and envelopes around price (trend-following or volatility-adapted)."),
    "correlation":        ("Correlation",
                           "Pair statistics: covariance, correlation, regression beta, hedge-adjusted spreads."),
    "data-handling":      ("Data handling",
                           "Clean, sanitize, or pre-process input -- NaN handling, outlier removal, clipping."),
    "geometry":           ("Geometry",
                           "2D coordinate conversions and related operations."),
    "math":               ("Math",
                           "Stateless arithmetic and scalar functions: abs, log, exp, trig, rounding."),
    "momentum":           ("Momentum",
                           "Rate-of-change indicators: outputs proportional to recent change in the input."),
    "oscillator":         ("Oscillator",
                           "Bounded indicators that swing between fixed extremes -- overbought/oversold logic."),
    "regression":         ("Regression",
                           "Fits a parametric model (line, polynomial) to a trailing window."),
    "risk":               ("Risk / Performance",
                           "Backtest-evaluation metrics: drawdowns, Sharpe/Sortino/Calmar ratios, hit rate."),
    "signal-processing":  ("Signal processing",
                           "DSP filters (IIR, FIR, state-space) and adaptive estimators."),
    "smoothing":          ("Smoothing",
                           "Filters whose primary purpose is noise reduction."),
    "statistics":         ("Statistics",
                           "Distributional summaries beyond mean/variance: order statistics, skewness, kurtosis, ranks."),
    "transforms":         ("Transforms",
                           "Element-wise or stateful series transformations: lag, diff, detrend, cumulative reductions, returns."),
    "trend":              ("Trend",
                           "Indicators that estimate the direction of a series -- moving averages and related."),
    "volatility":         ("Volatility",
                           "Estimators of dispersion / risk per unit time -- return-based, range-based, and bar-aware."),
    "volume":             ("Volume",
                           "Volume-aware indicators (OBV, AD line, MFI, VWAP, ...)."),
}

# Map implementation_family -> docs subdirectory (for the :doc: refs)
FAMILY_DIR = {
    "math":          "functions_math",
    "misc":          "functions_misc",
    "preprocessing": "functions_preprocessing",
    "rolling":       "functions_rolling",
    "ew":            "functions_ew",
    "fin":           "functions_fin",
    "signal":        "functions_signal",
}

GENERATED_BANNER = (
    ".. NOTE: This file is auto-generated by devtools/build_topic_pages.py\n"
    ".. Do not edit by hand. Re-run the script after updating help.json.\n\n"
)


def build_topic_page(topic: str, members: list[dict]) -> str:
    title, desc = TOPICS[topic]
    lines = [GENERATED_BANNER + title, "=" * len(title), "", desc, ""]
    if not members:
        lines += ["*(No functions currently in this topic.)*", ""]
        return "\n".join(lines)
    lines += ["", ".. list-table::", "   :header-rows: 1",
              "   :widths: 30 70", "",
              "   * - Function", "     - Description"]
    for m in sorted(members, key=lambda e: e["name"].lower()):
        family = m["implementation_family"]
        subdir = FAMILY_DIR.get(family, f"functions_{family}")
        doc_ref = f":doc:`{m['name']} </{subdir}/{m['name']}>`"
        short = (m.get("short") or "").replace("\n", " ").strip()
        lines += [f"   * - {doc_ref}",
                  f"     - {short}"]
    lines.append("")
    return "\n".join(lines)


def build_index_page() -> str:
    title = "Functions by topic"
    lines = [GENERATED_BANNER + title, "=" * len(title), "",
             "Browse all screamer functions grouped by use case. Each function may appear in more than one topic.",
             "",
             ".. toctree::",
             "   :maxdepth: 1",
             "   :titlesonly:",
             ""]
    for topic in sorted(TOPICS):
        lines.append(f"   by_topic/{topic}")
    lines.append("")
    return "\n".join(lines)


def main():
    data = json.loads(HELP_JSON.read_text())
    by_topic: dict[str, list[dict]] = {t: [] for t in TOPICS}
    for entry in data.values():
        for t in entry.get("topics") or []:
            if t in by_topic:
                by_topic[t].append(entry)
            else:
                # Catch typos / drift: if frontmatter references an
                # unknown topic, fail loudly.
                raise ValueError(
                    f"{entry['name']}: unknown topic {t!r}. Update "
                    "TOPICS in build_topic_pages.py or fix the frontmatter."
                )

    OUT_DIR.mkdir(exist_ok=True)
    for topic, members in by_topic.items():
        (OUT_DIR / f"{topic}.rst").write_text(build_topic_page(topic, members))
        print(f"  + by_topic/{topic}.rst  ({len(members)} functions)")
    INDEX_FILE.write_text(build_index_page())
    print(f"\nWrote {INDEX_FILE.relative_to(ROOT)} and {len(TOPICS)} topic pages.")


if __name__ == "__main__":
    main()
