#!/usr/bin/env python3
"""Auto-generate the grouped FUNCTIONS index from docs/topics.yml + help.json.

Output:
    docs/by_group_index.rst    -- the FUNCTIONS landing: a sphinx-design card grid
                                  of the 8 groups, plus a hidden toctree that homes
                                  every function reference page (so none are orphaned).
    docs/by_group/<slug>.rst   -- one page per GROUP; each has a section per member
                                  topic (docs/topics.yml order) with that topic's
                                  function table.

Run after every help.json update:
    poetry run python devtools/build_topic_pages.py
"""
import json
import re
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))
from devtools.topics import load_topics, load_groups, validate_groups

HELP_JSON = ROOT / "screamer" / "data" / "help.json"
DOCS = ROOT / "docs"
OUT_DIR = DOCS / "by_group"
OLD_DIR = DOCS / "by_topic"
INDEX_FILE = DOCS / "by_group_index.rst"

GENERATED_BANNER = (
    ".. NOTE: This file is auto-generated by devtools/build_topic_pages.py\n"
    ".. Do not edit by hand. Re-run the script after updating help.json.\n\n"
)
FM = re.compile(r"---\n(.*?)\n---\n", re.S)


def _page_refs() -> dict[str, str]:
    """name -> 'functions_<subdir>/<Name>' for every reference page that exists."""
    refs = {}
    for md in sorted(DOCS.glob("functions_*/*.md")):
        m = FM.match(md.read_text())
        if not m:
            continue
        name = (yaml.safe_load(m.group(1)) or {}).get("name")
        if name:
            refs[name] = f"{md.parent.name}/{md.stem}"
    return refs


def _table(members, refs, shorts, titles) -> list[str]:
    lines = [".. list-table::", "   :header-rows: 1", "   :widths: 30 70", "",
             "   * - Function", "     - Description"]
    for fn in members:
        ref = refs.get(fn)
        display = titles.get(fn, fn)
        doc_ref = f":doc:`{display} </{ref}>`" if ref else f"``{display}``"
        short = (shorts.get(fn) or "").replace("|", "\\|")
        lines += [f"   * - {doc_ref}", f"     - {short}"]
    lines.append("")
    return lines


def build_group_page(group, topics, members, refs, shorts, titles, homed) -> str:
    title = group["name"]
    lines = [GENERATED_BANNER + title, "=" * len(title), "", group["desc"], ""]
    for tslug in group["topics"]:
        meta = topics[tslug]
        heading = meta["name"]
        lines += [heading, "-" * len(heading), "", meta["desc"], ""]
        lines += _table(sorted(members.get(tslug, []), key=str.lower),
                        refs, shorts, titles)
    # Hidden toctree homes this group's function pages under it, so they nest in the
    # sidebar under the group (ordered by topic) instead of dumping flat on the
    # Functions landing.
    if homed:
        lines += [".. toctree::", "   :hidden:", ""]
        lines += [f"   /{ref}" for ref in homed]
        lines.append("")
    return "\n".join(lines)


def build_index(groups, leftover) -> str:
    lines = [GENERATED_BANNER + "Functions", "=========", "",
             "Every function, grouped by what it does. Pick a group to browse; "
             "the search box finds a function by name.", "",
             ".. grid:: 1 2 2 3", "   :gutter: 3", ""]
    for slug, g in groups.items():
        lines += [f"   .. grid-item-card:: {g['name']}",
                  f"      :link: by_group/{slug}", "      :link-type: doc", "",
                  f"      {g['desc']}", ""]
    # Hidden toctree homes the 8 group pages under this landing: the sidebar shows
    # the groups, the body shows only the cards (no duplicate list). Any function
    # page not homed under a group (a covered twin with no grouped topic) is homed
    # here as a fallback so nothing is orphaned.
    lines += [".. toctree::", "   :hidden:", ""]
    lines += [f"   by_group/{slug}" for slug in groups]
    lines += [f"   /{ref}" for ref in leftover]
    lines.append("")
    return "\n".join(lines)


def main():
    validate_groups()
    topics = load_topics()
    groups = load_groups()
    help_data = json.loads(HELP_JSON.read_text())
    refs = _page_refs()
    shorts = {n: e.get("short", "") for n, e in help_data.items()}
    titles = {n: e.get("title", n) for n, e in help_data.items()}

    # Table membership (visible rows): grouped, index:false twins excluded.
    members: dict[str, list[str]] = {slug: [] for slug in topics}
    for name, entry in help_data.items():
        if entry.get("index") is False:      # covered twins (_iter, Input, Node)
            continue
        for slug in entry.get("topics", []):
            if slug in members:
                members[slug].append(name)

    # Homing (sidebar nav): every function page is homed under exactly one group,
    # the first group (in group order) whose topics include one of its topics. This
    # includes index:false twins, so no page is orphaned; they are navigable but not
    # listed in the tables. Order within a group is topic order, then name.
    homed: dict[str, list[str]] = {slug: [] for slug in groups}
    seen: set[str] = set()
    for gslug, g in groups.items():
        for tslug in g["topics"]:
            fns = sorted((n for n, e in help_data.items()
                          if tslug in e.get("topics", []) and n in refs),
                         key=str.lower)
            for fn in fns:
                ref = refs[fn]
                if ref not in seen:
                    seen.add(ref)
                    homed[gslug].append(ref)
    leftover = sorted(set(refs.values()) - seen)   # pages with no grouped topic

    if OLD_DIR.exists():                      # drop the previous per-topic taxonomy
        for stale in OLD_DIR.glob("*.rst"):
            stale.unlink()
        OLD_DIR.rmdir()
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    for stale in OUT_DIR.glob("*.rst"):
        stale.unlink()
    for slug, group in groups.items():
        page = build_group_page(group, topics, members, refs, shorts, titles,
                                homed[slug])
        (OUT_DIR / f"{slug}.rst").write_text(page)

    INDEX_FILE.write_text(build_index(groups, leftover))
    listed = sum(len(members[t]) for g in groups.values() for t in g["topics"])
    print(f"Wrote {INDEX_FILE.name} and {len(groups)} group pages "
          f"({listed} listings, {len(seen)} homed + {len(leftover)} leftover "
          f"over {len(refs)} pages).")


if __name__ == "__main__":
    main()
