#!/usr/bin/env python3
"""Auto-generate the topic-based FUNCTIONS index from docs/topics.yml + help.json.

Output:
    docs/by_topic_index.rst   -- the FUNCTIONS landing: a visible toctree of the
                                 topic pages (docs/topics.yml order) plus a hidden
                                 toctree that includes every function reference
                                 page (so none are orphaned).
    docs/by_topic/<slug>.rst  -- one page per topic, listing the functions that
                                 declare it (index:false entries are skipped).

Run after every help.json update:
    poetry run python devtools/build_topic_pages.py
"""
import json
import re
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))
from devtools.topics import load_topics

HELP_JSON = ROOT / "screamer" / "data" / "help.json"
DOCS = ROOT / "docs"
OUT_DIR = DOCS / "by_topic"
INDEX_FILE = DOCS / "by_topic_index.rst"

GENERATED_BANNER = (
    ".. NOTE: This file is auto-generated by devtools/build_topic_pages.py\n"
    ".. Do not edit by hand. Re-run the script after updating help.json.\n\n"
)
FM = re.compile(r"---\n(.*?)\n---\n", re.S)


def _page_refs() -> dict[str, str]:
    """name -> 'functions_<subdir>/<Name>' for every reference page that exists."""
    refs = {}
    for md in sorted(DOCS.glob("functions_*/*.md")):
        m = FM.match(md.read_text())
        if not m:
            continue
        name = (yaml.safe_load(m.group(1)) or {}).get("name")
        if name:
            refs[name] = f"{md.parent.name}/{md.stem}"
    return refs


def build_topic_page(title: str, desc: str, members: list[str],
                     refs: dict[str, str], shorts: dict[str, str]) -> str:
    lines = [GENERATED_BANNER + title, "=" * len(title), "", desc, "",
             ".. list-table::", "   :header-rows: 1", "   :widths: 30 70", "",
             "   * - Function", "     - Description"]
    for fn in members:
        ref = refs.get(fn)
        doc_ref = f":doc:`{fn} </{ref}>`" if ref else f"``{fn}``"
        short = (shorts.get(fn) or "").replace("|", "\\|")
        lines += [f"   * - {doc_ref}", f"     - {short}"]
    lines.append("")
    return "\n".join(lines)


def build_index(topics: dict, all_refs: set[str]) -> str:
    # ``:orphan:`` keeps this landing page out of the sidebar: the left nav lists
    # the 20 topic pages directly under the "Functions" caption (see docs/index.rst).
    # The page stays reachable via in-text links (e.g. the notebooks) and still
    # homes every reference page through the hidden toctree below.
    lines = [":orphan:", "", GENERATED_BANNER + "Functions", "=========", "",
             "Every function, grouped by topic. Topics are many-to-many, so a "
             "function may appear under more than one.", ""]
    for slug, meta in topics.items():
        lines.append(f"* :doc:`{meta['name']} <by_topic/{slug}>`")
    # Hidden toctree so every reference page is included exactly once (no orphans).
    lines += ["", ".. toctree::", "   :hidden:", ""]
    lines += [f"   {ref}" for ref in sorted(all_refs)]
    lines.append("")
    return "\n".join(lines)


def main():
    topics = load_topics()
    help_data = json.loads(HELP_JSON.read_text())
    refs = _page_refs()
    shorts = {n: e.get("short", "") for n, e in help_data.items()}

    members: dict[str, list[str]] = {slug: [] for slug in topics}
    for name, entry in help_data.items():
        if entry.get("index") is False:      # covered twins (_iter, Input, Node)
            continue
        for slug in entry.get("topics", []):
            if slug in members:
                members[slug].append(name)

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    for stale in OUT_DIR.glob("*.rst"):      # drop the previous taxonomy's pages
        stale.unlink()
    for slug, meta in topics.items():
        page = build_topic_page(meta["name"], meta["desc"],
                                sorted(members[slug], key=str.lower), refs, shorts)
        (OUT_DIR / f"{slug}.rst").write_text(page)

    INDEX_FILE.write_text(build_index(topics, set(refs.values())))
    print(f"Wrote {INDEX_FILE.name} and {len(topics)} topic pages "
          f"({sum(len(m) for m in members.values())} listings over {len(refs)} pages).")


if __name__ == "__main__":
    main()
