import ast
import inspect
import os
import re
from devtools import sii

screamer_bindings_module = sii.load_local_screamer_binding()


def read_project_version(pyproject_path='pyproject.toml'):
    """Read version from pyproject.toml so it stays in sync with the package.

    Uses regex rather than tomllib so this works on Python 3.9 and 3.10 too
    (tomllib is 3.11+). The line format `version = "x.y.z"` is stable and is
    what bump-my-version edits, so this is robust enough.
    """
    with open(pyproject_path, 'r') as f:
        for line in f:
            m = re.match(r'\s*version\s*=\s*"([^"]+)"', line)
            if m:
                return m.group(1)
    raise RuntimeError(f"No version line found in {pyproject_path}")


def read_public_names(path):
    """Return the list in the given module's `__all__`, parsed statically."""
    with open(path, 'r') as f:
        tree = ast.parse(f.read(), filename=path)
    for node in tree.body:
        if isinstance(node, ast.Assign):
            for target in node.targets:
                if isinstance(target, ast.Name) and target.id == "__all__":
                    return [elt.value for elt in node.value.elts]
    return []


def generate_init_py(module, output_path='screamer/__init__.py'):
    version = read_project_version()

    # Internal machinery that pybind11 binds so functors can inherit from it or
    # return it, but which is not part of the public API. Kept out of the
    # exported namespace and __all__.
    internal = {
        "EvalOp", "ScreamerBase",           # functor base classes
        "AnextAwaitable", "Awaiter",         # async iteration helpers
        "LazyAsyncIterator", "LazyEvalIterator", "LazyIterator",
    }

    # Get all classes and functions not starting with an underscore
    public_members = [
        name for name, obj in inspect.getmembers(module)
        if name[0].isupper() and (inspect.isclass(obj) or inspect.isfunction(obj))
        and name not in internal
    ]

    stream_names = read_public_names('screamer/streams.py')
    if not stream_names:
        raise RuntimeError(
            "read_public_names('screamer/streams.py') returned empty — streams.__all__ missing or unparseable")

    dag_names = read_public_names('screamer/dag.py')
    if not dag_names:
        raise RuntimeError("dag.__all__ missing or unparseable")

    micro_names = read_public_names('screamer/microstructure.py')
    if not micro_names:
        raise RuntimeError("microstructure.__all__ missing or unparseable")

    backtest_names = read_public_names('screamer/backtest.py')
    if not backtest_names:
        raise RuntimeError("backtest.__all__ missing or unparseable")

    supervised_names = read_public_names('screamer/supervised.py')
    if not supervised_names:
        raise RuntimeError("supervised.__all__ missing or unparseable")

    # Prepare the content for __init__.py
    init_content = f'''# DO NOT MODIFY, THIS FILE IS AUTOGENERATED
# screamer/__init__.py

__version__ = "{version}"

from .screamer_bindings import (
    {", ".join(public_members)}
)

from .streams import (
    {", ".join(stream_names)}
)

from .dag import (
    {", ".join(dag_names)}
)

from .microstructure import (
    {", ".join(micro_names)}
)

from .backtest import (
    {", ".join(backtest_names)}
)

from .supervised import (
    {", ".join(supervised_names)}
)

__all__ = [
    {", ".join([f'"{name}"' for name in public_members + stream_names + dag_names + micro_names + backtest_names + supervised_names])}
]

# Wrap functor classes so each instance records its constructor arguments
# (powers readable reprs, Pipeline node labels, and Pipeline serialization).
from ._functor_params import install_param_capture
install_param_capture(globals())
'''

    # Write the content to the output file
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with open(output_path, 'w') as init_file:
        init_file.write(init_content)

    print(f"Generated {output_path} with {len(public_members)} members.")

# Load the module and generate __init__.py
if __name__ == "__main__":
    generate_init_py(screamer_bindings_module)
