import inspect
import os
import re
from devtools import sii

screamer_bindings_module = sii.load_local_screamer_binding()


def read_project_version(pyproject_path='pyproject.toml'):
    """Read version from pyproject.toml so it stays in sync with the package.

    Uses regex rather than tomllib so this works on Python 3.9 and 3.10 too
    (tomllib is 3.11+). The line format `version = "x.y.z"` is stable and is
    what bump-my-version edits, so this is robust enough.
    """
    with open(pyproject_path, 'r') as f:
        for line in f:
            m = re.match(r'\s*version\s*=\s*"([^"]+)"', line)
            if m:
                return m.group(1)
    raise RuntimeError(f"No version line found in {pyproject_path}")


def generate_init_py(module, output_path='screamer/__init__.py'):
    version = read_project_version()

    # Get all classes and functions not starting with an underscore
    public_members = [
        name for name, obj in inspect.getmembers(module)
        if name[0].isupper() and (inspect.isclass(obj) or inspect.isfunction(obj))
    ]

    # Prepare the content for __init__.py
    init_content = f'''# DO NOT MODIFY, THIS FILE IS AUTOGENERATED
# screamer/__init__.py

__version__ = "{version}"

from .screamer_bindings import (
    {", ".join(public_members)}
)

__all__ = [
    {", ".join([f'"{name}"' for name in public_members])}
]
'''

    # Write the content to the output file
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with open(output_path, 'w') as init_file:
        init_file.write(init_content)

    print(f"Generated {output_path} with {len(public_members)} members.")

# Load the module and generate __init__.py
if __name__ == "__main__":
    generate_init_py(screamer_bindings_module)
