#!/usr/bin/env python3
"""Generate Embind bindings (wasm/generated/bindings_wasm.cpp) from the wasm manifest.

For each op in devtools/wasm/wasm_manifest.json this emits, inside one
EMSCRIPTEN_BINDINGS(screamer) block that opens with SCREAMER_REGISTER_EVAL_OP_RUNTIME():

  * plain / transform ops:
      emscripten::class_<CppType, emscripten::base<screamer::EvalOp>>("Name")
          .constructor<CTOR_TYPES>();
    (empty <> for a no-arg ctor; transform ops use their exact cpp_type and a zero-arg ctor)

  * ew_optional ops (any std::optional<double> ctor arg):
    a free factory in an anonymous namespace,
      inline CppType* make_Name(<double per optional slot, plain type otherwise>) {
          return new CppType(<screamer_wasm::opt(x) for optional slots, x otherwise>);
      }
    then
      emscripten::class_<CppType, emscripten::base<screamer::EvalOp>>("Name")
          .constructor(&make_Name, emscripten::allow_raw_pointers());

The operator-header include set is copied verbatim from the nanobind bindings/*.cpp
files (the `#include "screamer/..."` lines), minus streams/dag headers and minus the
nanobind/base/dispatch/functor_base common headers, so the header set is exact.

Usage:
  python3 devtools/wasm/gen_wasm_bindings.py           # write the .cpp
  python3 devtools/wasm/gen_wasm_bindings.py --check    # validate coverage of the .cpp
  python3 devtools/wasm/gen_wasm_bindings.py --stdout   # write the generated .cpp to stdout, no write/check
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
MANIFEST = REPO / "devtools" / "wasm" / "wasm_manifest.json"
OUT = REPO / "wasm" / "generated" / "bindings_wasm.cpp"
BINDINGS_DIR = REPO / "bindings"

OPTIONAL_T = "std::optional<double>"

# Common headers that are nanobind-dependent or explicitly excluded per the brief.
# base.h / functor_base.h are pure but pulled in transitively; eval_op.h ships via
# embind_runtime.h; the rest drag in nanobind and must not reach the wasm compile.
EXCLUDED_HEADERS = {
    "screamer/common/base.h",
    "screamer/common/dispatch.h",
    "screamer/common/functor_base.h",
    "screamer/common/async_generator.h",
    "screamer/common/lazy_eval_iterator.h",
    "screamer/common/eval_op.h",  # already included by embind_runtime.h
}

INCLUDE_RE = re.compile(r'^\s*#include\s+"(screamer/[^"]+)"')


def load_manifest() -> list[dict]:
    return json.loads(MANIFEST.read_text())


def collect_op_headers() -> list[str]:
    """Union of `#include "screamer/..."` lines across the nanobind bindings,
    minus streams/dag and the excluded common headers."""
    headers: set[str] = set()
    for cpp in sorted(BINDINGS_DIR.glob("*.cpp")):
        for line in cpp.read_text().splitlines():
            m = INCLUDE_RE.match(line)
            if not m:
                continue
            hdr = m.group(1)
            if hdr.startswith("screamer/streams/") or hdr.startswith("screamer/dag/"):
                continue
            if hdr in EXCLUDED_HEADERS:
                continue
            headers.add(hdr)
    return sorted(headers)


def factory_name(op_name: str) -> str:
    return f"make_{op_name}"


def render_factory(op: dict) -> str:
    """Emit an ew_optional factory: doubles for optional slots, opt() to rewrap."""
    cpp = op["cpp_type"]
    name = op["name"]
    params, args = [], []
    for i, t in enumerate(op["ctor"]):
        pn = f"a{i}"
        if t == OPTIONAL_T:
            params.append(f"double {pn}")
            args.append(f"screamer_wasm::opt({pn})")
        else:
            params.append(f"{t} {pn}")
            args.append(pn)
    return (
        f"inline {cpp}* {factory_name(name)}({', '.join(params)}) {{\n"
        f"    return new {cpp}({', '.join(args)});\n"
        f"}}\n"
    )


def render_class(op: dict) -> str:
    cpp = op["cpp_type"]
    name = op["name"]
    head = f'emscripten::class_<{cpp}, emscripten::base<screamer::EvalOp>>("{name}")'
    if op["ctor_kind"] == "ew_optional":
        return f"    {head}\n        .constructor(&{factory_name(name)}, emscripten::allow_raw_pointers());"
    ctor_types = ", ".join(op["ctor"])
    return f"    {head}\n        .constructor<{ctor_types}>();"


def has_vector_ctor(ops: list[dict]) -> bool:
    return any(any("vector" in t for t in op["ctor"]) for op in ops)


def generate(ops: list[dict]) -> str:
    headers = collect_op_headers()
    ew = [op for op in ops if op["ctor_kind"] == "ew_optional"]

    lines: list[str] = []
    lines.append("// GENERATED by devtools/wasm/gen_wasm_bindings.py -- do not edit by hand.")
    lines.append("// Embind bindings for every point (event-wise) screamer op in the manifest.")
    lines.append("")
    lines.append('#include "embind_runtime.h"')
    for h in headers:
        lines.append(f'#include "{h}"')
    lines.append("")

    if ew:
        lines.append("// ---- ew_optional factories: JS passes NaN for a missing optional slot ----")
        lines.append("namespace {")
        for op in ew:
            lines.append(render_factory(op))
        lines.append("}  // namespace")
        lines.append("")

    lines.append("EMSCRIPTEN_BINDINGS(screamer) {")
    lines.append("    SCREAMER_REGISTER_EVAL_OP_RUNTIME();")
    if has_vector_ctor(ops):
        lines.append("    emscripten::register_vector<double>(\"VectorDouble\");")
    lines.append("")
    for op in ops:
        lines.append(render_class(op))
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def check(ops: list[dict]) -> int:
    if not OUT.exists():
        print(f"ERROR: {OUT} does not exist; run the generator first.", file=sys.stderr)
        return 1
    text = OUT.read_text()
    errors: list[str] = []

    class_names = re.findall(r'emscripten::class_<[^;]*?>\("([^"]+)"\)', text)
    # EvalOp is the base runtime class, not a manifest op.
    op_class_names = [n for n in class_names if n != "EvalOp"]

    from collections import Counter
    counts = Counter(op_class_names)
    for op in ops:
        c = counts.get(op["name"], 0)
        if c != 1:
            errors.append(f"op {op['name']!r} appears {c} times as class_<...>(\"Name\") (want 1)")

    manifest_names = {op["name"] for op in ops}
    for n in op_class_names:
        if n not in manifest_names:
            errors.append(f"class {n!r} in output is not in the manifest")

    ew = [op for op in ops if op["ctor_kind"] == "ew_optional"]
    for op in ew:
        if f"{factory_name(op['name'])}(" not in text:
            errors.append(f"ew_optional op {op['name']!r} has no {factory_name(op['name'])} factory")

    if errors:
        for e in errors:
            print(f"CHECK FAIL: {e}", file=sys.stderr)
        return 1

    print(f"BINDINGS OK: {len(op_class_names)} classes, {len(ew)} custom ctors")
    return 0


def main(argv: list[str]) -> int:
    ops = load_manifest()
    if "--check" in argv:
        return check(ops)
    if "--stdout" in argv:
        # Byte-identical to what a plain run writes to OUT, just routed to
        # stdout so callers (e.g. the freshness-gate test) can diff without
        # touching the committed file.
        sys.stdout.write(generate(ops))
        return 0
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(generate(ops))
    print(f"wrote {OUT} ({len(ops)} ops)")
    return check(ops)


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
